
Lmod is automatically replacing "nvhpc/21.9" with "gcc/11.2.0".


Lmod is automatically replacing "PrgEnv-nvhpc/8.3.3" with "PrgEnv-gnu/8.3.3".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.16

Error executing job with overrides: ['+mpi.local_size=4', '++data.stage=/local/scratch/', '+log.timestamp=ms_256', '+log.experiment_id=542568.polaris-pbs-01.hsn.cm.polaris.alcf.anl.gov']
Traceback (most recent call last):
  File "./main.py", line 185, in main
    return CosmoflowMain(cfg).exec()
  File "/lus/grand/projects/datascience/hzheng/mlperf-2022/optimized-hpc/cosmoflow/pytorch/utils/app.py", line 36, in exec
    self.setup()
  File "./main.py", line 132, in setup
    self._trainer.warmup(capture_stream=capture_stream)
  File "/lus/grand/projects/datascience/hzheng/mlperf-2022/optimized-hpc/cosmoflow/pytorch/trainer.py", line 271, in warmup
    self.scaler_.scale(loss).backward()
  File "/soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: NCCL error in: /soft/datascience/conda/2022-07-19/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:46, unhandled cuda error, NCCL version 2.10.3
ncclUnhandledCudaError: Call to CUDA function failed.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at /soft/datascience/conda/2022-07-19/pytorch/c10/cuda/CUDACachingAllocator.cpp:1387 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x95 (0x146cee53c2c5 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1ba68 (0x146cee790a68 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x236 (0x146cee795cf6 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x3ef608 (0x146d0205b608 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x146cee5209f5 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: <unknown function> + 0x3d25019 (0x146cfbbbc019 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::Reducer::~Reducer() + 0x31b (0x146cfbbace5b in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x9a0ff2 (0x146d0260cff2 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x9a498a (0x146d0261098a in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x33ed22 (0x146d01faad22 in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x33fbdf (0x146d01fabbdf in /soft/datascience/conda/2022-07-19/mconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x10faf5 (0x56215d543af5 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #12: <unknown function> + 0x1a9727 (0x56215d5dd727 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #13: <unknown function> + 0x10fa98 (0x56215d543a98 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #14: <unknown function> + 0x1a9727 (0x56215d5dd727 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #15: <unknown function> + 0x10faf5 (0x56215d543af5 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #16: <unknown function> + 0x1a9727 (0x56215d5dd727 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #17: <unknown function> + 0x1fe296 (0x56215d632296 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #18: <unknown function> + 0x12f9a2 (0x56215d5639a2 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #19: <unknown function> + 0x130406 (0x56215d564406 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #20: PyGC_Collect + 0x4f (0x56215d67012f in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #21: Py_FinalizeEx + 0x74 (0x56215d6874c4 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #22: Py_Exit + 0x8 (0x56215d6875f8 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #23: <unknown function> + 0x25363b (0x56215d68763b in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #24: <unknown function> + 0x253680 (0x56215d687680 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #25: PyRun_SimpleFileExFlags + 0x274 (0x56215d68a604 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #26: Py_RunMain + 0x3a9 (0x56215d68aa29 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #27: Py_BytesMain + 0x39 (0x56215d68ac29 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)
frame #28: __libc_start_main + 0xef (0x146d4a33524d in /lib64/libc.so.6)
frame #29: <unknown function> + 0x1f9ad7 (0x56215d62dad7 in /var/run/palsd/794df74d-f03d-4c9b-b556-c9f176712c98/files/python)

x3102c0s25b0n0.hsn.cm.polaris.alcf.anl.gov: rank 277 died from signal 6 and dumped core
